{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "flask-aws-monitor.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ required "ingress.class_name is required when ingress is enabled" .Values.ingress.class_name | quote }}
  rules:
    - host: {{ required "ingress.host is required when ingress is enabled" .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.pod.port }}
{{- end }}
